<template>
  <Avatar>
    <AvatarImage
      src="https://mighty.tools/mockmind-api/content/human/104.jpg"
      alt="@mighty.tools"
    />
    <AvatarFallback>CN</AvatarFallback>
  </Avatar>
</template>
